# This part should be on the input parameter of Rust api Function that got from frontend (Form).
@subscription_id = b116435e-6118-4db9-90bf-a5107f78c90f
@resourceGroups = beritasakti
@storageName = hashkelllearning
# Should in url encoded
@containerName = $web

PUT https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resourceGroups}}/providers/Microsoft.Storage/storageAccounts/{{storageName}}/blobServices/default/containers/{{containerName}}?api-version=2023-01-01
Content-Type: application/json

{
	"properties": {
		"publicAccess": "Blob"
	}
}

### Success = Response Code: 201 body: (inside NewContainer.reponse.json) <-< is Example
### Success(Already Has The Container) = Response Code: 201 body: (inside NewContainer.reponse.json) <-< is Example
### Failed = Response Code: non-200 body: (See below)
###         {"error":{"code":"ResourceGroupNotFound","message":"message value in here"}} <-< Only shiw message on the frontend