# Doc -> https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/create?view=rest-storagerp-2023-01-01&tabs=HTTP#examples
# Bagian ini harus menjadi parameter input dari fungsi API Rust yang diterima dari frontend (Form).
# https://login.microsoftonline.com/common/oauth2/authorize?client_id=04b07795-8ddb-461a-bbee-02f971519268&response_type=code&redirect_uri=http://localhost:5173&resource=https://storage.azure.com/&state=1234567890
@subscription_id = b116435e-6118-4db9-90bf-a5107f78c90f
@resourceGroups = beritasakti
@storageName = hashkelllearning

# Bagian ini bisa dari parameter tetapi nilai di bawah ini adalah nilai default.
@location = Southeast Asia
@kind = StorageV2
@accessTier = Hot
@allowBlobPublicAccess = true
@allowSharedKeyAccess = true
@skuName = Standard_GRS
@skuTier = Standard

# Untuk mendapatkan token Authorization, Anda perlu mengimplementasikan OAuth 2.0 atau menggunakan Managed Identity jika berjalan di Azure.
# Contoh menggunakan token yang sudah ada:
@authToken = "ey... (token lengkap di sini)"

PUT https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resourceGroups}}/providers/Microsoft.Storage/storageAccounts/{{storageName}}?api-version=2023-01-01
Content-Type: application/json
Authorization: Bearer {{authToken}}

# Ini adalah body permintaan
{
	"kind": "{{kind}}",
	"location": "{{storageName}}",
	"properties": {
        "accessTier": "{{accessTier}}",
        "allowBlobPublicAccess": {{allowBlobPublicAccess}},
        "allowSharedKeyAccess": {{allowSharedKeyAccess}}
    },
	"sku": {
        "name": "{{skuName}}",
        "tier": "{{skuTier}}"
    }
}

### Accepted = Response Code: 202 body: (kosong) <-< Sedang diproses, harus melakukan permintaan ulang dengan operasi yang sama dalam 10 atau 15 detik (Frontend akan menampilkan gambar atau indikator loading)
### (Harus Diterima terlebih dahulu) Sukses = Response Code: 200|201 body: (di dalam NewStorage.response.json) <-< Contoh
### Gagal = Response Code: non-200 body: (Lihat di bawah)
###         {"error":{"code":"ResourceGroupNotFound","message":"nilai pesan di sini"}} <-< Hanya tampilkan pesan di frontend

