@subscription_id = b116435e-6118-4db9-90bf-a5107f78c90f
@resourcesGroups = beritasakti
@storageName = hashkelllearning
POST https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resourcesGroups}}/providers/Microsoft.Storage/storageAccounts/{{storageName}}/ListAccountSas?api-version=2023-01-01
Content-Type: application/json

{
	"signedExpiry": "2024-06-04T16:59:53.043Z",
	"signedPermission": "rwdlacup",
	"signedResourceTypes": "sco",
	"signedServices": "bfqt",
	"keyToSign": "key1"
}

### response:
### {
###     "accountSasToken": "sv=2015-04-05&ss=bfqt&srt=sco&sp=rwdlacup&se=2024-06-04T16%3A59%3A53.0430000Z&sig=pSl0U%2BtMfns35pFw11uSDrEkxIfdBYva9oU%2BVdcXxXw%3D"
### }